# Generated by Django 3.2.9 on 2021-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task_text',
            field=models.TextField(max_length=100),
        ),
    ]
